[package]
name = "bevy_2d_transform_hierarchy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.8"
default-features = false
features = ["render", "bevy_asset"]

[dev-dependencies]
bevy = "0.8"
bevy_despawn_with = "0.11.0"